"""Filename → known sales title. Used only after the owner deposits a copy.

The tuple is append-only, not a freeze. A new purchased file can land in
incoming/ anytime; add needles here when the filename should be recognized.
Only CORE_CATALOG_IDS unlock SFT rows. Other mapped titles are archive.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class KnownTitle:
    catalog_id: str
    title: str
    author: str
    year: int | None
    licence: str
    proposed_use: str
    knowledge_ids: tuple[str, ...]
    filename_needles: tuple[str, ...]
    # Distinctive short phrases; if found, provenance may become page-located.
    # Do not store the surrounding page text in git.
    markers: tuple[str, ...]
    polarity: str = "positive"  # positive | negative | skip


# Conversation-sales titles that may unlock companion SFT rows.
# Everything else is archive: registered, not emitted into derived JSONL.
CORE_CATALOG_IDS = frozenset(
    {
        "spin-selling",
        "challenger-sale",
        "influence",
        "never-split-the-difference",
        "fanatical-prospecting",
        "sandler-rules",
        "getting-to-yes",
        "selling-to-big-companies",
        "agile-selling",
        "storybrand",
        "storybrand-2",
        "storybrand-funnel",
        "rysev-active-sales",
        "hbr-sales",
        "brody-email",
        "zaid-sales-bible",
        "hsieh-service",
    }
)


def corpus_lane(catalog_id: str | None) -> str:
    if catalog_id in CORE_CATALOG_IDS:
        return "core"
    return "archive"


KNOWN_TITLES: tuple[KnownTitle, ...] = (
    KnownTitle(
        catalog_id="spin-selling",
        title="SPIN Selling",
        author="Neil Rackham",
        year=1988,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=("candidate-discovery-spin-001",),
        filename_needles=(
            "spin selling",
            "spin_selling",
            "spinselling",
            "rackham",
            "рекхэм",
            "рекхем",
            "спин-продажи",
            "спин продажи",
        ),
        markers=(
            "situation question",
            "need-payoff",
            "need payoff",
            "implication question",
            "ситуационн",
            "извлекающ",
            "направляющ",
        ),
    ),
    KnownTitle(
        catalog_id="challenger-sale",
        title="The Challenger Sale",
        author="Matthew Dixon and Brent Adamson",
        year=2011,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=("candidate-presentation-challenger-teaching-002",),
        filename_needles=(
            "challenger sale",
            "challenger_sale",
            "the challenger",
            "чемпионы продаж",
            "диксон",
        ),
        markers=(
            "commercial teaching",
            "challenger",
            "constructive tension",
            "челленджер",
            "чемпион продаж",
        ),
    ),
    KnownTitle(
        catalog_id="influence",
        title="Influence: The Psychology of Persuasion",
        author="Robert Cialdini",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule (reciprocity/consistency); scarcity is negative unless DNA has a real limit",
        knowledge_ids=(
            "candidate-objection-price-cialdini-reciprocity-003a",
            "candidate-objection-price-cialdini-consistency-003b",
            "candidate-general-cialdini-scarcity-003e",
        ),
        filename_needles=(
            "influence",
            "cialdini",
            "чалдини",
            "психология согласия",
            "психология влияния",
        ),
        markers=(
            "reciprocity",
            "social proof",
            "scarcity",
            "взаимность",
            "социальное доказательство",
            "дефицит",
        ),
    ),
    KnownTitle(
        catalog_id="never-split-the-difference",
        title="Never Split the Difference",
        author="Chris Voss and Tahl Raz",
        year=2016,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=("candidate-objection-diagnostic-question-voss-004",),
        filename_needles=(
            "never split",
            "never_split",
            "chris voss",
            "voss",
            "восс",
            "никаких компромиссов",
        ),
        markers=(
            "calibrated question",
            "labeling",
            "that's right",
            "калиброванн",
            "никаких компромиссов",
        ),
    ),
    KnownTitle(
        catalog_id="fanatical-prospecting",
        title="Fanatical Prospecting",
        author="Jeb Blount",
        year=2015,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=("candidate-followup-cadence-multitouch-005",),
        filename_needles=(
            "fanatical prospecting",
            "fanatical_prospecting",
            "jeb blount",
            "blount",
            "блаунт",
            "фанатичные продажи",
        ),
        markers=("prospecting", "multi-touch", "follow-up", "фанатичн", "проспектинг"),
    ),
    KnownTitle(
        catalog_id="scientific-advertising",
        title="Scientific Advertising",
        author="Claude C. Hopkins",
        year=1923,
        licence="public domain in the U.S. (1923); still do not commit the scan",
        proposed_use="positive_rule",
        knowledge_ids=("candidate-step1-hopkins-specific-claims-011",),
        filename_needles=("scientific advertising", "scientific_advertising", "hopkins"),
        markers=("specific", "test", "sample"),
    ),
    KnownTitle(
        catalog_id="sandler-rules",
        title="The Sandler Rules",
        author="David Mattson",
        year=2009,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("sandler rules", "49 законов продаж", "мэттсон", "маттсон"),
        markers=("sandler", "i.o.u.", "закон", "сэндер"),
    ),
    KnownTitle(
        catalog_id="getting-to-yes",
        title="Getting to Yes",
        author="Roger Fisher, William Ury, and Bruce Patton",
        year=1981,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=(
            "getting to yes",
            "переговоры без поражения",
            "фишер",
        ),
        markers=("batna", "interest", "позиции", "интересы"),
    ),
    KnownTitle(
        catalog_id="selling-to-big-companies",
        title="Selling to Big Companies",
        author="Jill Konrath",
        year=2006,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("selling to big", "большим компаниям"),
        markers=("big companies", "большим компаниям", "trigger"),
    ),
    KnownTitle(
        catalog_id="agile-selling",
        title="Agile Selling",
        author="Jill Konrath",
        year=2014,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("agile selling", "гибкие продажи"),
        markers=("agile", "гибкие продажи"),
    ),
    KnownTitle(
        catalog_id="storybrand-2",
        title="Building a StoryBrand 2.0",
        author="Donald Miller",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("метод storybrand 2", "storybrand 2 0", "storybrand 2.0"),
        markers=("storybrand", "герой", "проводник"),
    ),
    KnownTitle(
        catalog_id="storybrand",
        title="Building a StoryBrand",
        author="Donald Miller",
        year=2017,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("метод storybrand", "building a storybrand"),
        markers=("storybrand", "герой", "проводник"),
    ),
    KnownTitle(
        catalog_id="storybrand-funnel",
        title="Marketing Made Simple",
        author="Donald Miller and Dr. J.J. Peterson",
        year=2020,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule",
        knowledge_ids=(),
        filename_needles=("воронки продаж", "marketing made simple"),
        markers=("funnel", "воронк", "storybrand"),
    ),
    KnownTitle(
        catalog_id="give-and-take",
        title="Give and Take",
        author="Adam Grant",
        year=2013,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule only when DNA already authorizes a free step; otherwise skip invented reciprocity",
        knowledge_ids=(),
        filename_needles=("give and take", "брать или отдавать", "адам грант"),
        markers=("giver", "taker", "отдавать", "брать"),
        polarity="positive",
    ),
    KnownTitle(
        catalog_id="never-eat-alone",
        title="Never Eat Alone",
        author="Keith Ferrazzi",
        year=2005,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for generous follow-up; spray-and-pray networking is skip",
        knowledge_ids=(),
        filename_needles=("never eat alone", "ешьте в одиночку", "феррацци"),
        markers=("сеть", "щедрость", "завтрак"),
    ),
    KnownTitle(
        catalog_id="learned-optimism",
        title="Learned Optimism",
        author="Martin E. P. Seligman",
        year=1990,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for tone; outcome guarantees stay negative",
        knowledge_ids=(),
        filename_needles=("learned optimism", "научиться оптимизму", "селигман"),
        markers=("оптимизм", "выученн", "беспомощн"),
    ),
    KnownTitle(
        catalog_id="eat-that-frog",
        title="Eat That Frog!",
        author="Brian Tracy",
        year=2001,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for doing the hard follow-up first; not a customer-pressure tactic",
        knowledge_ids=(),
        filename_needles=("eat that frog", "съешьте лягушку", "трейси"),
        markers=("лягушк", "приоритет", "самое важное"),
    ),
    KnownTitle(
        catalog_id="presence",
        title="Presence",
        author="Amy Cuddy",
        year=2015,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for calm tone; skip power-posing as a sales trick",
        knowledge_ids=(),
        filename_needles=("присутствие духа", "эми кадди", "amy cuddy"),
        markers=("присутствие", "уверенность", "поза"),
    ),
    KnownTitle(
        catalog_id="what-every-body-is-saying",
        title="What Every BODY is Saying",
        author="Joe Navarro and Marvin Karlins",
        year=2008,
        licence="closed; owner-deposited copy required",
        proposed_use="skip in SMS/chat; negative if the mouth claims it can read the body",
        knowledge_ids=(),
        filename_needles=("наварро", "о чём вы думаете", "о чем вы думаете", "what every body"),
        markers=("жест", "кластер", "базов"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="nudge",
        title="Nudge",
        author="Richard H. Thaler and Cass R. Sunstein",
        year=2008,
        licence="closed; owner-deposited copy required",
        proposed_use="negative_counterexample unless DNA already has a real default the customer chose",
        knowledge_ids=(),
        filename_needles=("nudge", "архитектура выбора", "талер"),
        markers=("подталкиван", "архитектур", "выбор"),
        polarity="negative",
    ),
    KnownTitle(
        catalog_id="predictably-irrational",
        title="Predictably Irrational",
        author="Dan Ariely",
        year=2008,
        licence="closed; owner-deposited copy required",
        proposed_use="negative_counterexample for invented anchors, fake free, or comparison prices",
        knowledge_ids=(),
        filename_needles=("предсказуемая иррациональность", "ариели", "predictably irrational"),
        markers=("якорь", "бесплатн", "иррационал"),
        polarity="negative",
    ),
    KnownTitle(
        catalog_id="thinking-fast-slow",
        title="Thinking, Fast and Slow",
        author="Daniel Kahneman",
        year=2011,
        licence="closed; owner-deposited copy required",
        proposed_use="negative_counterexample for System-1 fake urgency; diagnose slowly",
        knowledge_ids=(),
        filename_needles=("thinking, fast and slow", "thinking fast and slow", "канеман"),
        markers=("system 1", "система 1", "эвристик"),
        polarity="negative",
    ),
    KnownTitle(
        catalog_id="crossing-the-chasm",
        title="Crossing the Chasm",
        author="Geoffrey A. Moore",
        year=1991,
        licence="closed; owner-deposited copy required",
        proposed_use="skip as a chat script; positioning, not a customer turn",
        knowledge_ids=(),
        filename_needles=("преодоление пропасти", "crossing the chasm", "джеффри а. мур", "geoffrey"),
        markers=("пропаст", "ранние последователи", "chasm"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="hbr-sales",
        title="HBR on Sales",
        author="Harvard Business Review",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule only for diagnose/confirm; skip corporate-process dump",
        knowledge_ids=(),
        filename_needles=("harvard business review", "hbr) — продажи", "hbr — продажи"),
        markers=("продаж", "клиент"),
    ),
    KnownTitle(
        catalog_id="rysev-active-sales",
        title="Активные продажи",
        author="Nikolay Rysev",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for one discovery question; skip pressure closes",
        knowledge_ids=(),
        filename_needles=("активные продажи", "рысев"),
        markers=("активн", "переговор"),
    ),
    KnownTitle(
        catalog_id="brody-email",
        title="Email Persuasion / Продающие рассылки",
        author="Ian Brody",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for a single next step in writing; skip blast-pack offers",
        knowledge_ids=(),
        filename_needles=("продающие рассылки", "ян броди", "ian brody"),
        markers=("рассылк", "email"),
    ),
    KnownTitle(
        catalog_id="zaid-sales-bible",
        title="Библия продаж XXI века",
        author="Yaniv Zaid",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule only where it matches spec 0.4; skip hard close",
        knowledge_ids=(),
        filename_needles=("библия продаж", "йанив заид", "yaniv zaid"),
        markers=("убежден", "переговор"),
    ),
    KnownTitle(
        catalog_id="azimov-sales-practice",
        title="Продажи, переговоры. Практика, примеры",
        author="Sergey Azimov",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip call-center scripts; negative if it hammers close",
        knowledge_ids=(),
        filename_needles=("аширович азимов", "сергей аширович"),
        markers=("переговор", "практик"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="dyak-phone-sales",
        title="Техника продаж для новичков",
        author="Alexander Dyak",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip as call-center formula; not companion tone",
        knowledge_ids=(),
        filename_needles=("техника продаж для новичков", "александр дьяк"),
        markers=("телефон", "новичк"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="verchinsky-sales",
        title="Продажи и переговоры",
        author="Anatoly Verchinsky",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip demo-lecture tone; map only, no SFT until reviewed",
        knowledge_ids=(),
        filename_needles=("верчинский", "смотрите, как надо"),
        markers=("переговор", "продаж"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="potapov-sales-marketing",
        title="Маркетинг продаж",
        author="Dmitry Potapov",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip as a marketing textbook; not a chat turn",
        knowledge_ids=(),
        filename_needles=("дмитрий потапов", "потапов — маркетинг продаж"),
        markers=("маркетинг", "продаж"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="hsieh-service",
        title="Exceptional Customer Service",
        author="Tony Hsieh",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="positive_rule for warm tone; skip invented wow-gifts",
        knowledge_ids=(),
        filename_needles=("tony hsieh", "exceptional customer service", "тони хси"),
        markers=("service", "customer"),
    ),
    KnownTitle(
        catalog_id="bankin-content",
        title="Контент-маркетинг для роста продаж",
        author="Alexander Bankin",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip as a content calendar; not a live sales turn",
        knowledge_ids=(),
        filename_needles=("контент-маркетинг для роста", "александр михайлович банкин"),
        markers=("контент", "воронк"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="zhdanova-lazy-marketing",
        title="Ленивый маркетинг",
        author="Tamara Zhdanova",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip passive-funnel lore; STOP still outranks nurture",
        knowledge_ids=(),
        filename_needles=("ленивый маркетинг", "тамара сергеевна жданова"),
        markers=("пассивн", "ленив"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="nordfalt-retail",
        title="Ритейл-маркетинг",
        author="Jens Nordfält",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip store layout; not SMS/chat companion",
        knowledge_ids=(),
        filename_needles=("ритейл-маркетинг", "йенс нордфальт"),
        markers=("ритейл", "полк"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="traindl-retail-brand",
        title="Мастерство ритейл-брендинга",
        author="Arndt Traindl",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="skip branding textbook",
        knowledge_ids=(),
        filename_needles=("ритейл-брендинг", "арндт трайндл"),
        markers=("бренд", "ритейл"),
        polarity="skip",
    ),
    KnownTitle(
        catalog_id="gautrey-dirty-tricks",
        title="21 Dirty Tricks at Work",
        author="Colin Gautrey",
        year=None,
        licence="closed; owner-deposited copy required",
        proposed_use="negative_counterexample; office politics is not a sales move",
        knowledge_ids=(),
        filename_needles=("21 dirty tricks", "colin gautrey"),
        markers=("trick", "office"),
        polarity="negative",
    ),
)


SKIP_FILENAMES = frozenset(
    {
        "readme.md",
        "sales_training_project.zip",
        "sales_training_project.readme.md",
        "licence-sidecar.example.json",
        ".gitkeep",
    }
)

BOOK_SUFFIXES = frozenset({".pdf", ".epub", ".fb2", ".txt", ".md", ".html", ".htm", ".docx"})


def match_known_title(filename: str) -> KnownTitle | None:
    stem = filename.rsplit(".", 1)[0] if "." in filename else filename
    hay = f"{stem} {filename}".replace("-", " ").replace("_", " ").casefold()
    hits = [item for item in KNOWN_TITLES if any(needle in hay for needle in item.filename_needles)]
    if len(hits) == 1:
        return hits[0]
    if len(hits) > 1:
        # Prefer the longest needle match so "the challenger sale" beats "sale".
        return max(
            hits,
            key=lambda item: max(len(n) for n in item.filename_needles if n in hay),
        )
    return None
